# Production repo: https://github.com/Event-Pro/event-pro-api

name: Push to external repo

on:
  pull_request:
    branches: "*"

jobs:
  push-to-external-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pushes to external repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: .
          destination-github-username: "event-pro"
          destination-repository-name: "event-pro-api"
